    [theme]
    # Primary accent color for interactive elements.
    primaryColor = "#FF9000"

    # Background color for the main content area.
    backgroundColor = "#E2E8CE"

    # Background color used for the sidebar and most interactive widgets.
    secondaryBackgroundColor = "#ACBFA4"

    # Color used for almost all text.
    textColor = "#262626"